### ISSUE TITLE
Enable GitHub Pages?

### ISSUE THREAD

**Issue by swharden** [1Marc/todomvc-vanillajs-2022#4]
This is a fun project! Thanks for creating and sharing it.

I may be overlooking it, but I don't see a link I can click to test this (without downloading the repo). I'm on my phone, and it would be nice to have a link to a live version of this.

Consider enabling GitHub Pages for this repo and linking to that URL in the project description and/or readme.

**Comment by 1Marc** [comment]
Oh good idea! Yes I’ll do that.

**Comment by 1Marc** [comment]
I got it working! https://1marc.github.io/todomvc-vanillajs-2022/

Cheers and thanks for the suggestion.

**Comment by swharden** [comment]
Nice! 🚀

**Comment by jwdunn1** [comment]
Updated path: https://1marc.github.io/modern-todomvc-vanillajs
