### ISSUE TITLE
No web components?

### ISSUE THREAD

**Issue by nicojs** [1Marc/todomvc-vanillajs-2022#6]
Why did you decide not to use web components? Use of shadow DOM might not be needed (although it couldn't hurt either), but custom elements might be a nice addition.

**Comment by 1Marc** [comment]
This guy took a shot at using web components: https://github.com/HipsterBrown/todomvc-vanillajs-2022/

https://twitter.com/hipsterbrown/status/1522766350820773888?s=20&t=j_0x2T_FW4oe_iSFttIz4w

Hmm 🤔 Maybe I could expand this repo to include some other solutions. The current a todoMVC project hasn’t been touched in years.
