### ISSUE TITLE
it looks like we could get rid of the regular expression

### ISSUE THREAD

**Issue by jt3k** [1Marc/todomvc-vanillajs-2022#8]
It looks like there is no difference.
But it's still nice to read the simple .slice(1)

Here https://github.com/1Marc/todomvc-vanillajs-2022/blob/5509f8645ed98ada2b7ca7d31f299dde231cc5c4/js/helpers.js#L5

**Comment by 1Marc** [comment]
Hmm, yeah something like `document.location.hash.slice(2)` would work and be a bit simpler, but either works. The regex is a bit more exact so people can see what I'm doing, IMO.

Thanks for the tip though!
